test <- gsub("XxZzYyAuthorsXxZzYy", XxZzYyAuthorsXxZzYy, test)
test <- gsub("XxZzYyProdDateXxZzYy", XxZzYyProdDateXxZzYy, test)
test <- gsub("XxZzYyGeoCovXxZzYy", XxZzYyGeoCovXxZzYy, test)
test <- gsub("XxZzYyMethodsXxZzYy", XxZzYyMethodsXxZzYy, test)
test <- gsub("XxZzYyVarsXxZzYy", XxZzYyVarsXxZzYy, test)
test <- gsub("XxZzYyKeyWrdsXxZzYy", XxZzYyKeyWrdsXxZzYy, test)
test <- gsub("XxZzYyColPeriodXxZzYy", XxZzYyColPeriodXxZzYy, test)
test <- gsub("XxZzYyDataColsXxZzYy", XxZzYyDataColsXxZzYy, test)
test <- gsub("XxZzYyAbsXxZzYy", XxZzYyAbsXxZzYy, test)
test <- gsub("XxZzYyTimePeriodXxZzYy", XxZzYyTimePeriodXxZzYy, test)


test <- gsub("XxZzYyIndicatorXxZzYy", XxZzYyIndicatorXxZzYy, test)
test <- gsub("XxZzYyTitleXxZzYy", XxZzYyTitleXxZzYy, test)
test <- gsub("XxZzYyIndicNoSpaceXxZzYy", XxZzYyIndicNoSpaceXxZzYy, test)
test <- gsub("XxZzYyObsAfricaXxZzYy", XxZzYyObsAfricaXxZzYy, test)
test <- gsub("XxZzYyObsTotalXxZzYy", XxZzYyObsTotalXxZzYy, test)
test <- gsub("XxZzYyObsOceaniaXxZzYy", XxZzYyObsOceaniaXxZzYy, test)
test <- gsub("XxZzYyObsEuropeXxZzYy", XxZzYyObsEuropeXxZzYy, test)
test <- gsub("XxZzYyObsAsiaXxZzYy", XxZzYyObsAsiaXxZzYy, test)
test <- gsub("XxZzYyObsAmericasXxZzYy", XxZzYyObsAmericasXxZzYy, test)

test <- gsub("XxZzYyArithmeticMeanXxZzYy", XxZzYyArithmeticMeanXxZzYy, test)
test <- gsub("XxZzYyMINXxZzYy", XxZzYyMINXxZzYy, test)
test <- gsub("XxZzYyQRT1XxZzYy", XxZzYyQRT1XxZzYy, test)
test <- gsub("XxZzYyMEDIANXxZzYy", XxZzYyMEDIANXxZzYy, test)
test <- gsub("XxZzYyQRT3XxZzYy", XxZzYyQRT3XxZzYy, test)
test <- gsub("XxZzYyMAXXxZzYy", XxZzYyMAXXxZzYy, test)
test <- gsub("XxZzYyDataQualityXxZzYy", XxZzYyDataQualityXxZzYy, test)
test <- gsub("XxZzYyGenRefHTMLXxZzYy", XxZzYyGenRefHTMLXxZzYy, test)
test <- gsub("XxZzYyGenRefsXxZzYy", XxZzYyGenRefsXxZzYy, test)
#test <- gsub("XxZzYySourcesHTMLXxZzYy", XxZzYySourcesHTMLXxZzYy, test)
#test <- gsub("XxZzYySourcesXxZzYy", XxZzYySourcesXxZzYy, test)

# Obs. per period
test <- gsub("XxZzYyObsP1XxZzYy", XxZzYyObsP1XxZzYy, test)
test <- gsub("XxZzYyObsP2XxZzYy", XxZzYyObsP2XxZzYy, test)
test <- gsub("XxZzYyObsP3XxZzYy", XxZzYyObsP3XxZzYy, test)
test <- gsub("XxZzYyObsP4XxZzYy", XxZzYyObsP4XxZzYy, test)
test <- gsub("XxZzYyObsP5XxZzYy", XxZzYyObsP5XxZzYy, test)
test <- gsub("XxZzYyObsP6XxZzYy", XxZzYyObsP6XxZzYy, test)

# newly added, not in excel
test <- gsub("XxZzYyGraph0XxZzYy", XxZzYyGraph0XxZzYy, test)
test <- gsub("XxZzYyGraph1XxZzYy", XxZzYyGraph1XxZzYy, test)
test <- gsub("XxZzYyGraph2XxZzYy", XxZzYyGraph2XxZzYy, test)
test <- gsub("XxZzYyGraph3XxZzYy", XxZzYyGraph3XxZzYy, test)
test <- gsub("XxZzYyGraph4XxZzYy", XxZzYyGraph4XxZzYy, test)
test <- gsub("XxZzYyGraph5XxZzYy", XxZzYyGraph5XxZzYy, test)
test <- gsub("XxZzYyGraph6XxZzYy", XxZzYyGraph6XxZzYy, test)
test <- gsub("XxZzYyGraph7XxZzYy", XxZzYyGraph7XxZzYy, test)
test <- gsub("XxZzYyGraph8XxZzYy", XxZzYyGraph8XxZzYy, test)
#test <- gsub("XxZzYyTotalNumOfCountriesXxZzYy", XxZzYyTotalNumOfCountriesXxZzYy, test)
#test <- gsub("XxZzYyTotalDatasetsXxZzYy", XxZzYyTotalDatasetsXxZzYy, test)
test <- gsub("XxZzYyDataVerseLinkXxZzYy", XxZzYyDataVerseLinkXxZzYy, test)
test <- gsub("XxZzYyWebServerFile1XxZzYy", XxZzYyWebServerFile1XxZzYy, test)
test <- gsub("XxZzYyWebServerFile2XxZzYy", XxZzYyWebServerFile2XxZzYy, test)
test <- gsub("XxZzYyCitationStringXxZzYy", XxZzYyCitationStringXxZzYy, test)
test <- gsub("XxZzYyWorkingPaperXxZzYy", XxZzYyWorkingPaperXxZzYy, test)
#test <- gsub("XxZzYyAboutClioInfraXxZzYy", XxZzYyAboutClioInfraXxZzYy, test)

